---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data/_project-categories
  label: Catégories (projet)
  create: documents
  match: "**/*"
  templates:
  - categorie-projet
- type: directory
  path: data/_testimonials
  label: Témoignages
  create: documents
  match: "**/*"
  templates:
  - temoignage
- type: document
  path: data/config.json
  label: Configuration
- type: directory
  path: data/_projects
  label: Projets
  create: documents
  match: "**/*"
  templates:
  - projet-new
upload_dir: public/cms
public_path: "/cms"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
